name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: add some file
        run: echo "yay " >> test.md

      - name: cd to parent
        run: cd ../

      - name: echo it works
        run: echo it actually works
        
      - uses: EndBug/add-and-commit@v9
        with:
          #default_author: github_actions
          author_name: Ivan
          author_email: 127977316+ivan-developer-01@users.noreply.github.com
          committer_name: because of that
          committer_email: nobodyknows@fullivanstack.com
          message: "yay to you toy\n\nCo-Authored-By: Tiger <tigera@ivananimals.com>\nCo-Authored-By: Lion <lion@ivananimals.com>\nCo-Authored-By: Yolwoocle <54135715+Yolwoocle@users.noreply.github.com>\nCo-Authored-By: PouletRaPHOO <70721948+pouletRaphoo@users.noreply.github.com>\nCo-Authored-By: Linus Torvalds <1024025+torvalds@users.noreply.github.com>\nCo-Authored-By: utopy <30875147+utopyin@users.noreply.github.com>\nCo-Authored-By: Theobosse <60153892+theobosse@users.noreply.github.com>\nCo-Authored-By: Gouspourd <71386539+gouspourd@users.noreply.github.com>\nCo-Authored-By: Maxio <91082344+maximcosta@users.noreply.github.com>\nCo-Authored-By: Notgoyome <43115206+Yauyau123@users.noreply.github.com>\nCo-Authored-By: Antoine Roucau <76783848+Antoine-roucau@users.noreply.github.com>\nCo-Authored-By: PoulpitoGDL <86129726+PoulpitoGDL@users.noreply.github.com>"
