name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: add some file
        run: echo "yay " >> test.md

      - name: cd to parent
        run: cd ../

      - name: echo it works
        run: echo it actually works
        
      - uses: EndBug/add-and-commit@v9
        with:
          #default_author: github_actions
          author_name: Ivan
          author_email: 127977316+ivan-developer-01@users.noreply.github.com
          committer_name: NobodyKnows
          committer_email: nobodyknows@fullivanstack.com
          message: "yay to you toy"
